#CNN.yaml
model:
  conv1:
    in_channels: 1
    kernel_size: 3
    out_channels: 16
    padding: 0
  dropout_conv_rate: 0.2
  dropout_fc_rate: 0.2
  fc1:
    out_features: 32
  fc2:
    out_features: 2
  input_shape:
  - 1
  - 30
  - 30
